name: CI - FitBeat Testing

on:
  push:
    branches:
      - main
      - master
      - '*'
  pull_request:
    branches:
      - main
      - master
      - '*'
  workflow_dispatch:  # Allows manual triggering explicitly

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout code explicitly
        uses: actions/checkout@v4

      - name: Set up Python 3.11 explicitly
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies explicitly
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify OPENAI_API_KEY explicitly
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "Explicit Error: OPENAI_API_KEY is EMPTY!"
            exit 1
          else
            echo "OPENAI_API_KEY is set explicitly and loaded successfully."
          fi

      - name: Explicitly Test OpenAI API Connectivity
        run: |
          pip install openai
          python - <<EOF
          import os
          import openai
          openai.api_key = os.getenv('OPENAI_API_KEY')
          try:
              models = openai.Model.list()
              print('Explicit API Call Successful:', models)
          except Exception as e:
              print('Explicit OpenAI API call error:', e)
              exit(1)
          EOF

      - name: Run explicit unit tests with pytest
        run: |
          pytest tests/
