name: CI - FitBeat Testing

on:
  push:
    branches:
      - main
      - master
      - '*'
  pull_request:
    branches:
      - main
      - master
      - '*'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # Explicitly set the env variable

    steps:
    - name: Checkout code explicitly
      uses: actions/checkout@v4

    - name: Set up Python 3.11 explicitly
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies explicitly
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run explicit unit tests with pytest
      run: |
        pytest tests/
